services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hoppscotch
      - POSTGRES_PASSWORD=hoppscotch
      - POSTGRES_DB=hoppscotch
    networks:
      - hoppscotch

  users-service:
    build:
      context: users
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=hoppscotch
      - POSTGRES_PASSWORD=hoppscotch
      - POSTGRES_DATABASE=hoppscotch
    depends_on:
        - postgres
    networks:
        - hoppscotch

  orders-service:
    build:
      context: orders
      dockerfile: Dockerfile
    ports:
      - 3100:3100
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=hoppscotch
      - POSTGRES_PASSWORD=hoppscotch
      - POSTGRES_DATABASE=hoppscotch
    depends_on:
        - postgres
    networks:
        - hoppscotch

  products-service:
    build:
      context: products
      dockerfile: Dockerfile
    ports:
      - 3200:3200
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USERNAME=hoppscotch
      - POSTGRES_PASSWORD=hoppscotch
      - POSTGRES_DATABASE=hoppscotch
    depends_on:
        - postgres
    networks:
        - hoppscotch


networks:
  hoppscotch:
    driver: bridge