x-service-common:
  &service-common
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USERNAME=hoppscotch
    - POSTGRES_PASSWORD=hoppscotch
    - POSTGRES_DATABASE=hoppscotch
  depends_on:
    - postgres
  networks:
    - hoppscotch


services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hoppscotch
      - POSTGRES_PASSWORD=hoppscotch
      - POSTGRES_DB=hoppscotch
    networks:
      - hoppscotch

  users-service:
    <<: *service-common
    build:
      context: users
      dockerfile: Dockerfile
    ports:
      - 3000:3000

  orders-service:
    <<: *service-common
    build:
      context: orders
      dockerfile: Dockerfile
    ports:
      - 3100:3100

  products-service:
    <<: *service-common
    build:
      context: products
      dockerfile: Dockerfile
    ports:
      - 3200:3200


networks:
  hoppscotch:
    driver: bridge