services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hoppscotch
      - POSTGRES_PASSWORD=hoppscotch
      - POSTGRES_DB=hoppscotch