x-service-common:
  &service-common
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_USERNAME=hoppscotch
    - POSTGRES_PASSWORD=hoppscotch
    - POSTGRES_DATABASE=hoppscotch
  depends_on:
    - postgres
  networks:
    - hoppscotch


services:
  gateway:
    image: nginx:latest
    container_name: gateway
    hostname: gateway
    restart: always
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/html:/etc/nginx/html
    networks:
      - hoppscotch
    depends_on:
      - users-service
      - orders-service
      - products-service

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    hostname: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hoppscotch
      - POSTGRES_PASSWORD=hoppscotch
      - POSTGRES_DB=hoppscotch
    networks:
      - hoppscotch

  users-service:
    <<: *service-common
    build:
      context: users
      dockerfile: Dockerfile

  orders-service:
    <<: *service-common
    build:
      context: orders
      dockerfile: Dockerfile

  products-service:
    <<: *service-common
    build:
      context: products
      dockerfile: Dockerfile


networks:
  hoppscotch:
    driver: bridge